# Generated by Django 3.0.4 on 2020-04-22 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('buildpantry', '0005_auto_20200405_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='history',
            fields=[
                ('number', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.TimeField()),
                ('recipe_searched', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildpantry.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('dateofbirth', models.DateField()),
                ('profilepicture', models.ImageField(default='pics/avatar.jpg', upload_to='pics')),
                ('favourites', models.ManyToManyField(related_name='favouriteof', to='buildpantry.recipe')),
                ('searchhistory', models.ManyToManyField(through='userprofile.history', to='buildpantry.recipe')),
            ],
        ),
        migrations.AddField(
            model_name='history',
            name='userprofile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.profile'),
        ),
        migrations.AddConstraint(
            model_name='history',
            constraint=models.UniqueConstraint(fields=('userprofile', 'recipe_searched', 'timestamp'), name='unique_history'),
        ),
    ]
