# Generated by Django 3.0.4 on 2020-04-22 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'ordering': ['-timestamp']},
        ),
    ]
