# Generated by Django 3.0.4 on 2020-06-29 16:33

from django.db import migrations, models
import userprofile.models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profilepicture',
            field=models.ImageField(default='pics/avatar.jpg', upload_to=userprofile.models.get_file_path),
        ),
    ]
