# Generated by Django 2.2.11 on 2020-03-16 09:21

import buildpantry.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ingredient',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('category', models.CharField(choices=[('condiments', 'condiments'), ('Legumes', 'Legumes'), ('Seasonings', 'Seasonings'), ('Alcohol', 'Alcohol'), ('Added Sweetners', 'Added Sweetners'), ('Dairy Alternatives', 'Dairy Alternatives'), ('Oils', 'Oils'), ('Nuts', 'Nuts'), ('Meats', 'Meats'), ('Vegetables', 'Vegetables'), ('Seafood', 'Seafood'), ('Fruits', 'Fruits'), ('Dairy', 'Dairy'), ('Fish', 'Fish'), ('Desserts&Snacks', 'Desserts&Snacks'), ('Soup', 'Soup'), ('Baking & Grains', 'Baking & Grains'), ('Spices', 'Spices'), ('Sauces', 'Sauces'), ('Beverages', 'Beverages')], max_length=25)),
                ('image', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='recipe',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=60)),
                ('description', models.TextField()),
                ('image', djongo.models.fields.ArrayField(model_container=buildpantry.models.image)),
                ('ingredientdetails', djongo.models.fields.ArrayField(model_container=buildpantry.models.ingredientused)),
                ('timetocook', djongo.models.fields.EmbeddedField(model_container=buildpantry.models.time, null=True)),
                ('instructions', models.TextField()),
                ('cuisine', models.CharField(choices=[('Chinese', 'Chinese'), ('Indian', 'Indian'), ('Italian', 'Italian'), ('Mexican', 'Mexican'), ('Southern', 'Southen'), ('Thai', 'Thai')], max_length=25)),
                ('dishtype', models.CharField(choices=[('Appetizers & Snacks', 'Appetizers & Snacks'), ('Bread Recipes', 'Bread Recipes'), ('Cake Recipes', 'Cake Recipes'), ('Candy and Fudge', 'Candy and Fudge'), ('Casserole Recipes', 'Casserole Recipes'), ('Christmas Cookies', 'Christmas Cookies'), ('Cocktail Recipes', 'Cocktail Recipes'), ('Cookie Recipes', 'Cookie Recipes'), ('Mac and Cheese Recipes', 'Mac and Cheese Recipes'), ('Main Dish', 'Main Dish'), ('Pasta Salad Recipes', 'Pasta Salad Recipes'), ('Pasta Recipes', 'Pasta Recipes'), ('Pie Recipes', 'Pie Recipes'), ('Pizza', 'Pizza'), ('Sandwiches', 'Sandwiches'), ('Sauces and Condiments', 'Sauces and Condiments'), ('Smoothie Recipes', 'Smoothie Recipes'), ('Soups, Stews, and Chili', 'Soups, Stews, and Chili'), ('Side Dish', 'Side Dish'), ('Salad', 'Salad')], max_length=25)),
                ('mark', models.CharField(choices=[('green', 'green'), ('red', 'red'), ('yellow', 'yellow')], max_length=7)),
            ],
        ),
    ]
