# Generated by Django 2.2.11 on 2020-03-15 07:39

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ingredient',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('category', models.CharField(choices=[('condiments', 'condiments'), ('Legumes', 'Legumes'), ('Seasonings', 'Seasonings'), ('Alcohol', 'Alcohol'), ('Added Sweetners', 'Added Sweetners'), ('Dairy Alternatives', 'Dairy Alternatives'), ('Oils', 'Oils'), ('Nuts', 'Nuts'), ('Meats', 'Meats'), ('Vegetables', 'Vegetables'), ('Seafood', 'Seafood'), ('Fruits', 'Fruits'), ('Dairy', 'Dairy'), ('Fish', 'Fish'), ('Desserts&Snacks', 'Desserts&Snacks'), ('Soup', 'Soup'), ('Baking & Grains', 'Baking & Grains'), ('Spices', 'Spices'), ('Sauces', 'Sauces'), ('Beverages', 'Beverages')], max_length=25)),
                ('image', models.TextField()),
            ],
        ),
    ]
