# Generated by Django 3.0.4 on 2020-03-30 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildpantry', '0002_recipe_mealtype'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ingredientList',
            new_name='ingredientUsed',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(max_length=60, primary_key=True, serialize=False),
        ),
    ]
