# Generated by Django 3.0.4 on 2020-04-04 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildpantry', '0003_auto_20200331_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='mark',
            field=models.CharField(choices=[('green', 'Veg'), ('red', 'NonVeg'), ('yellow', 'Contains Egg')], max_length=7),
        ),
    ]
